### ISSUE TITLE
Refactor offer filters to be selected by name

### ISSUE THREAD

**Issue by mwl** [ContainerSolutions/mesos-starter#17]
Like `mesos.resources.filter=distinctHost` rather than `mesos.resources.distinctHost=true`

**Comment by mwl** [comment]
I'm currently looking into configuration layout. Some filters needs parameters as well, for instance the scale.

If we're doing it the Spring way, it'll look something like this, which I don't find very elegant.

```yaml
mesos:
  resources:
    filter:
      distinctSlave:
        enabled: true
      scale:
        enabled: true
        factor: 3
```
 So I'm open for suggestions.
