### ISSUE TITLE
Let scheduler maintain different kinds of tasks

### ISSUE THREAD

**Issue by mwl** [ContainerSolutions/mesos-starter#51]
Two main usage patterns has come up to back this feature
* Compositions of schedulers. One "main" scheduler can maintain another scheduler
* Server/agent applications, like CI servers and some SQL databases

**Comment by mwl** [comment]
I suggest a configuration format where tasks are put into a task field

```yaml
spring:
  application:
    name: Sample App

mesos:
  tasks:
    - name: server
      command: nc -l ${SERVER_PORT}
      docker:
        image: alpine
      resources:
        count: 1
        cpus: 0.1
        mem: 64
        ports:
          server-port:
            host: 31101
            container: 80
    - name: slave
      command: sleep 200
      docker:
        image: alpine
      resources:
        count: 1
        cpus: 0.1
        mem: 64
```

Only new thing is that `mesos.*` has been moved into `mesos.tasks[n].*` and a `mesos.tasks[n].name` has been added.

Another solution is moving `mesos.*` properties into `mesos.tasks.name.*`
